use std::fs::{self, OpenOptions};
use std::io::{self, Write};
use std::os::unix::fs::{OpenOptionsExt, PermissionsExt};
use std::path::Path;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FstabEntry {
    pub source: String,
    pub target: String,
    pub fstype: String,
    pub options: Vec<String>,
    pub dump: u8,
    pub pass: u8,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FstabRecord {
    pub line_index: usize,
    pub entry: FstabEntry,
}

impl FstabEntry {
    pub fn new(
        source: impl Into<String>,
        target: impl Into<String>,
        fstype: impl Into<String>,
        options: Vec<String>,
    ) -> io::Result<Self> {
        let entry = Self {
            source: source.into(),
            target: target.into(),
            fstype: fstype.into(),
            options,
            dump: 0,
            pass: 0,
        };
        for value in [&entry.source, &entry.target, &entry.fstype] {
            if value.is_empty() || value.contains(['\n', '\r', '\0']) {
                return Err(io::Error::new(
                    io::ErrorKind::InvalidInput,
                    "fstab fields must be non-empty single-line strings",
                ));
            }
        }
        if entry
            .options
            .iter()
            .any(|value| value.contains(['\n', '\r', '\0']))
        {
            return Err(io::Error::new(
                io::ErrorKind::InvalidInput,
                "fstab options must not contain newlines",
            ));
        }
        Ok(entry)
    }

    pub fn render(&self) -> String {
        let options = if self.options.is_empty() {
            "defaults".to_string()
        } else {
            self.options.join(",")
        };
        format!(
            "{} {} {} {} {} {}",
            escape_field(&self.source),
            escape_field(&self.target),
            escape_field(&self.fstype),
            escape_field(&options),
            self.dump,
            self.pass
        )
    }

    pub fn parse(line: &str) -> io::Result<Self> {
        let fields = line.split_whitespace().take(6).collect::<Vec<_>>();
        if fields.len() < 4 {
            return Err(io::Error::new(
                io::ErrorKind::InvalidInput,
                "fstab entry requires source, target, filesystem type, and options",
            ));
        }
        let options = unescape_field(fields[3])
            .split(',')
            .filter(|option| !option.is_empty())
            .map(str::to_string)
            .collect();
        let mut entry = Self::new(
            unescape_field(fields[0]),
            unescape_field(fields[1]),
            unescape_field(fields[2]),
            options,
        )?;
        entry.dump = parse_number(fields.get(4).copied(), "dump")?;
        entry.pass = parse_number(fields.get(5).copied(), "pass")?;
        Ok(entry)
    }

    pub fn export_new(&self, path: &Path) -> io::Result<()> {
        let mut file = OpenOptions::new()
            .write(true)
            .create_new(true)
            .mode(0o600)
            .open(path)?;
        writeln!(file, "# Generated by mount-tui")?;
        writeln!(file, "{}", self.render())?;
        file.sync_all()
    }

    pub fn append_to(&self, path: &Path) -> io::Result<()> {
        let rendered = self.render();
        let source = escape_field(&self.source);
        let target = escape_field(&self.target);
        let existing = fs::read_to_string(path)?;
        if existing.lines().any(|line| {
            let line = line.trim_start();
            if line.is_empty() || line.starts_with('#') {
                return false;
            }
            let mut fields = line.split_whitespace();
            fields.next() == Some(source.as_str()) && fields.next() == Some(target.as_str())
        }) {
            return Err(io::Error::new(
                io::ErrorKind::AlreadyExists,
                format!(
                    "an fstab entry for {} on {} already exists",
                    self.source, self.target
                ),
            ));
        }

        let mut file = OpenOptions::new().append(true).open(path)?;
        if !existing.is_empty() && !existing.ends_with('\n') {
            writeln!(file)?;
        }
        writeln!(file, "{rendered}")?;
        file.sync_all()
    }
}

pub fn read_fstab(path: &Path) -> io::Result<Vec<FstabRecord>> {
    Ok(fs::read_to_string(path)?
        .lines()
        .enumerate()
        .filter_map(|(line_index, line)| {
            let line = line.trim();
            (!line.is_empty() && !line.starts_with('#'))
                .then(|| FstabEntry::parse(line).ok())
                .flatten()
                .map(|entry| FstabRecord { line_index, entry })
        })
        .collect())
}

pub fn replace_fstab_entry(path: &Path, line_index: usize, entry: &FstabEntry) -> io::Result<()> {
    rewrite_fstab(path, line_index, Some(entry.render()))
}

pub fn remove_fstab_entry(path: &Path, line_index: usize) -> io::Result<()> {
    rewrite_fstab(path, line_index, None)
}

fn rewrite_fstab(path: &Path, line_index: usize, replacement: Option<String>) -> io::Result<()> {
    let existing = fs::read_to_string(path)?;
    let mut lines = existing.lines().map(str::to_string).collect::<Vec<_>>();
    if line_index >= lines.len() {
        return Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            "fstab entry is stale; refresh and try again",
        ));
    }
    match replacement {
        Some(replacement) => lines[line_index] = replacement,
        None => {
            lines.remove(line_index);
        }
    }
    let mut updated = lines.join("\n");
    updated.push('\n');

    let file_name = path
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or("fstab");
    let backup = path.with_file_name(format!("{file_name}.mount-tui.bak"));
    if !backup.exists() {
        fs::copy(path, &backup)?;
    }
    let temp = path.with_file_name(format!(".{file_name}.mount-tui-{}.tmp", std::process::id()));
    let mode = fs::metadata(path)?.permissions().mode() & 0o7777;
    let mut file = OpenOptions::new()
        .write(true)
        .create_new(true)
        .mode(mode)
        .open(&temp)?;
    if let Err(error) = (|| -> io::Result<()> {
        file.write_all(updated.as_bytes())?;
        file.sync_all()?;
        drop(file);
        fs::rename(&temp, path)
    })() {
        let _ = fs::remove_file(&temp);
        return Err(error);
    }
    Ok(())
}

fn parse_number(value: Option<&str>, name: &str) -> io::Result<u8> {
    value.unwrap_or("0").parse().map_err(|_| {
        io::Error::new(
            io::ErrorKind::InvalidInput,
            format!("invalid fstab {name} value"),
        )
    })
}

fn escape_field(value: &str) -> String {
    let mut escaped = String::with_capacity(value.len());
    for ch in value.chars() {
        match ch {
            '\\' => escaped.push_str("\\134"),
            ' ' => escaped.push_str("\\040"),
            '\t' => escaped.push_str("\\011"),
            '#' => escaped.push_str("\\043"),
            _ => escaped.push(ch),
        }
    }
    escaped
}

fn unescape_field(value: &str) -> String {
    let bytes = value.as_bytes();
    let mut result = Vec::with_capacity(bytes.len());
    let mut index = 0;
    while index < bytes.len() {
        if bytes[index] == b'\\'
            && index + 3 < bytes.len()
            && let Ok(octal) = std::str::from_utf8(&bytes[index + 1..index + 4])
            && let Ok(decoded) = u8::from_str_radix(octal, 8)
        {
            result.push(decoded);
            index += 4;
            continue;
        }
        result.push(bytes[index]);
        index += 1;
    }
    String::from_utf8_lossy(&result).into_owned()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn renders_escaped_fstab_text() {
        let entry = FstabEntry::new(
            "/dev/disk/by-label/My Drive",
            "/media/alice/My Drive",
            "ext4",
            vec!["rw".into(), "nofail".into()],
        )
        .unwrap();
        assert_eq!(
            entry.render(),
            "/dev/disk/by-label/My\\040Drive /media/alice/My\\040Drive ext4 rw,nofail 0 0"
        );
    }

    #[test]
    fn append_rejects_duplicate_source_and_target() {
        let dir = std::env::temp_dir().join(format!("mount-tui-fstab-{}", std::process::id()));
        let path = dir.join("fstab");
        fs::create_dir_all(&dir).unwrap();
        fs::write(&path, "# test\n").unwrap();
        let entry =
            FstabEntry::new("UUID=abc", "/mnt/data", "ext4", vec!["defaults".into()]).unwrap();
        entry.append_to(&path).unwrap();
        assert_eq!(
            entry.append_to(&path).unwrap_err().kind(),
            io::ErrorKind::AlreadyExists
        );
        fs::remove_dir_all(dir).unwrap();
    }

    #[test]
    fn parses_replaces_and_removes_entries_without_losing_comments() {
        let dir = std::env::temp_dir().join(format!("mount-tui-fstab-edit-{}", std::process::id()));
        let path = dir.join("fstab");
        fs::create_dir_all(&dir).unwrap();
        fs::write(
            &path,
            "# keep this\nUUID=old /media/My\\040Drive ext4 defaults 0 2\n",
        )
        .unwrap();
        let records = read_fstab(&path).unwrap();
        assert_eq!(records[0].entry.target, "/media/My Drive");
        let mut replacement = records[0].entry.clone();
        replacement.source = "UUID=new".to_string();
        replace_fstab_entry(&path, records[0].line_index, &replacement).unwrap();
        assert!(
            fs::read_to_string(&path)
                .unwrap()
                .starts_with("# keep this\nUUID=new ")
        );
        remove_fstab_entry(&path, records[0].line_index).unwrap();
        assert_eq!(fs::read_to_string(&path).unwrap(), "# keep this\n");
        fs::remove_dir_all(dir).unwrap();
    }
}
